# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fetch_base_cpp <- function(x, res) {
    .Call('_windfetchR_fetch_base_cpp', PACKAGE = 'windfetchR', x, res)
}

